#!/usr/bin/sh

#Copyright (c) 2015 Hullu2000, Andy Morris, Tosmarcel

#Permission is hereby granted, free of charge, to any person obtaining
#a copy of this software and associated documentation files (the
#"Software"), to deal in the Software without restriction, including
#without limitation the rights to use, copy, modify, merge, publish,
#distribute, sublicense, and/or sell copies of the Software, and to
#permit persons to whom the Software is furnished to do so, subject to
#the following conditions:

#The above copyright notice and this permission notice shall be included
#in all copies or substantial portions of the Software.

#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
#CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

set -e

UTIME=$(date +%s%3N)
mkdir -p ~/.gc
touch ~/.gc/log

usage () {
	cat <<-EOF >&2
	gc: $1
	Usage:
	    gc d FILENAME      Delete FILENAME
	    gc r TIMESTAMP     Recover file deleted at time TIMESTAMP
	    gc l               View deletion log and timestamps
	    gc empty           Empty the log and remove all deleted files
	EOF
	exit 1
}

[ "$#" -gt 0 ] || usage "No command specified"

case "$1" in
	d)
		case "$#" in
			1) usage "No filename specified" ;;
			2) ;;
			*) usage "Too many arguments"
		esac
		[ -f "$2" ] || usage "File not found"

		mv "$2" ~/.gc/"$UTIME"
		xz ~/.gc/"$UTIME"
		echo "$PWD/$2" > ~/.gc/"$UTIME".log
		echo $PWD/$2 deleted at $UTIME | tee ~/.gc/log
		;;

	p)
		case "$#" in
			1) usage "No filename specified" ;;
			2) ;;
			*) usage "Too many arguments"
		esac

		xzcat ~/.gc/${2}.xz | less -S
		;;

	r)
		case "$#" in
			1) usage "No timestamp specified" ;;
			2) ;;
			*) usage "Too many arguments"
		esac
		[ -f ~/.gc/"$2".xz ] || usage "Timestamp not found"

		xz -d ~/.gc/"$2".xz
		mv ~/.gc/"$2" "$(cat ~/.gc/${2}.log)"
		rm ~/.gc/"$2".log
		# POSIX sed doesn't seem to have the -i option :(
		cp ~/.gc/log ~/.gc/log.bak
		sed "/$2/d" ~/.gc/log.bak > ~/.gc/log
		rm ~/.gc/log.bak
		;;

	l)
		case "$#" in
			1) ;;
			*) usage "Too many arguments"
		esac

		cat ~/.gc/log
		;;

	empty)
		case "$#" in
			1) ;;
			*) usage "Too many arguments"
		esac

		rm  ~/.gc/*
		;;

	*)
		usage "Command \`$1' unrecognised"
esac
