#!/usr/bin/sh

#Copyright (c) 2015 Hullu2000

#Permission is hereby granted, free of charge, to any person obtaining
#a copy of this software and associated documentation files (the
#"Software"), to deal in the Software without restriction, including
#without limitation the rights to use, copy, modify, merge, publish,
#distribute, sublicense, and/or sell copies of the Software, and to
#permit persons to whom the Software is furnished to do so, subject to
#the following conditions:

#The above copyright notice and this permission notice shall be included
#in all copies or substantial portions of the Software.

#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
#CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

set -e

UTIME=$(date +%s%3N)
mkdir -p ~/.gc
touch ~/.gc/log

if [ "$1" = "d" ]; then
	mv "$2" "~/.gc/$UTIME"
	xz "~/.gc/$UTIME"
	echo "$PWD/$2" > "~/.gc/${UTIME}.log"
	echo $PWD/$2 deleted at $UTIME >> ~/.gc/log
fi

if [ "$1" = "r" ]; then
	xz -d "~/.gc/${2}.xz"
	mv "~/.gc/$2" "$(cat ~/.gc/${2}.log)"
	rm "~/.gc/${2}.log"
fi

if [ "$1" = "l" ]; then
	cat ~/.gc/log
fi
if [ "$1" = "empty" ]; then
	rm  ~/.gc/*
fi
